name: Doc Linter

on: [pull_request]

jobs:
  doc-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: npm ci

    - name: run linter
      run: npm test
